DROP TABLE PRODUCT_DETAIL;

DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
	P_ID VARCHAR2(20) PRIMARY KEY,
	P_NAME VARCHAR2(20) NOT NULL,
	PRICE NUMBER NOT NULL,
	DES VARCHAR2(100)
);

INSERT INTO PRODUCT VALUES('LT-SS1', '상성노트북',2000000,'갤럭시북');
INSERT INTO PRODUCT VALUES('LT-LG1', 'LG노트북',2200000,'그램');
INSERT INTO PRODUCT VALUES('PC-AP1', '애픅멕북',3000000,'mac');

SELECT * FROM PRODUCT;
