selectAll = SELECT * FROM MYTEST

selectOne = SELECT * FROM MYTEST WHERE MNO = ?

insert = INSERT INTO MYTEST VALUES(SEQ_MEMBER.NEXTVAL, ?,?)

update = UPDATE MYTEST SET MNAME = ?, NICKNAME =? WHERE MNO = ?

delete = DELETE MYTEST WHERE MNO = ?