SELECT * FROM DEPARTMENT JOIN EMPLOYEE ON(DEPT_ID = DEPT_CODE) WHERE DEPT_CODE = 'D5';

SELECT * FROM EMPLOYEE;

SELECT * FROM PRODUCT;

DROP TABLE MEMBER;

CREATE SEQUENCE SEQ_MEMBER NOCACHE;
CREATE TABLE MEMBER(
	M_NO NUMBER PRIMARY KEY,
	M_NAME VARCHAR2(20) NOT NULL,
	M_AGE NUMBER NOT NULL,
	M_GENDER CHAR(3) CHECK(M_GENDER IN('M','F')) NOT NULL,
	M_LOCATION VARCHAR2(20),
	M_JOB VARCHAR2(20),
	M_TEL VARCHAR2(20),
	M_EMAIL VARCHAR2(20)
);

INSERT INTO MEMBER VALUES(SEQ_MEMBER.NEXTVAL, '레몬팡', 20, 'M', '성남', '개발자', '010-1234-5678', 'lemon@mail.com');

SELECT * FROM MEMBER;